services:
  apache:
    image: httpd:latest
    container_name: apache-server
    volumes:
      - ./src/main/resources/static:/usr/local/apache2/htdocs/  
    ports:
      - "8080:80"
    restart: always
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge  
